<a href="https://colab.research.google.com/github/ancestor9/2026_Spring_Application_Programming/blob/main/week4/webcrawl_quote_to_scrape.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Web Crwaling and Scrapping 실습**

### Text mining

In [15]:
from sklearn.feature_extraction.text import CountVectorizer
corpus = [
    'This is the first document.',
    'This document is the second document.',
    'And this is the third one.',
    'Is this the first document?',
]
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)
print(vectorizer.get_feature_names_out())
print(X.toarray())

['and' 'document' 'first' 'is' 'one' 'second' 'the' 'third' 'this']
[[0 1 1 1 0 0 1 0 1]
 [0 2 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1]]

In [16]:
import pandas as pd
pd.DataFrame(X.toarray(),
             columns = vectorizer.get_feature_names_out())

   and  document  first  is  one  second  the  third  this
0    0         1      1   1    0       0    1      0     1
1    0         2      0   1    0       1    1      0     1
2    1         0      0   1    1       0    1      1     1
3    0         1      1   1    0       0    1      0     1

In [17]:
vectorizer2 = CountVectorizer(analyzer='word', ngram_range=(2, 2))
X2 = vectorizer2.fit_transform(corpus)
vectorizer2.get_feature_names_out()

pd.DataFrame(X2.toarray(),
             columns = vectorizer2.get_feature_names_out())

,and this,document is,first document,is the,is this,second document,the first,the second,the third,third one,this document,this is,this the
0,0,0,1,1,0,0,1,0,0,0,0,1,0
1,0,1,0,1,0,1,0,1,0,0,1,0,0
2,1,0,0,1,0,0,0,0,1,1,0,1,0
3,0,0,1,0,1,0,1,0,0,0,0,0,1

## http://quotes.toscrape.com/ 에서 문장을 추출하여
### 1. 가장 많이 나오는 단어와 출현 빈도 구하기
### 2. 각 문장을 출현단어 여부에 따라 수치형 데이터로 변환하기(Countervector)

In [19]:
import requests
from bs4 import BeautifulSoup

In [20]:
url = "http://quotes.toscrape.com/"
response = requests.get(url)
soup = BeautifulSoup(response.text, "html.parser")

for quote in soup.find_all("span", class_="text"):
    print(quote.text)

“The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”
“It is our choices, Harry, that show what we truly are, far more than our abilities.”
“There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.”
“The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.”
“Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.”
“Try not to become a man of success. Rather become a man of value.”
“It is better to be hated for what you are than to be loved for what you are not.”
“I have not failed. I've just found 10,000 ways that won't work.”
“A woman is like a tea bag; you never know how strong it is until it's in hot water.”
“A day without sunshine is like, you know, night.”

In [21]:
quotes = [quote.text for quote in soup.find_all("span", class_="text")]
quotes

['“The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”',
 '“It is our choices, Harry, that show what we truly are, far more than our abilities.”',
 '“There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.”',
 '“The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.”',
 "“Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.”",
 '“Try not to become a man of success. Rather become a man of value.”',
 '“It is better to be hated for what you are than to be loved for what you are not.”',
 "“I have not failed. I've just found 10,000 ways that won't work.”",
 "“A woman is like a tea bag; you never know how strong it is until it's in hot water.”",
 '“A day without sunshine is like, you know, night.”']

In [22]:
texts = []
for quote in soup.find_all("span", class_="text"):
    # 따옴표를 제거한 텍스트
    cleaned_text = quote.text.strip('“”')
    print(cleaned_text)
    texts.append(cleaned_text)
print(texts)

The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.
It is our choices, Harry, that show what we truly are, far more than our abilities.
There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.
The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.
Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.
Try not to become a man of success. Rather become a man of value.
It is better to be hated for what you are than to be loved for what you are not.
I have not failed. I've just found 10,000 ways that won't work.
A woman is like a tea bag; you never know how strong it is until it's in hot water.
A day without sunshine is like, you know, night.
['The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.', 'It is our choices, Harry, that show what we truly are, far more than our abilities.', 'There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.', 'The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.', "Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.", 'Try not to become a man of success. Rather become a man of value.', 'It is better to be hated for what you are than to be loved for what you are not.', "I have not failed. I've just found 10,000 ways that won't work.", "A woman is like a tea bag; you never know how strong it is until it's in hot water.", 'A day without sunshine is like, you know, night.']

In [23]:
# text mining을 위해서는 corpus를 이렇게 반드시 저장
texts = [ quote.text.strip('“”') for quote in soup.find_all("span", class_="text")]
texts

['The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.',
 'It is our choices, Harry, that show what we truly are, far more than our abilities.',
 'There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.',
 'The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.',
 "Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.",
 'Try not to become a man of success. Rather become a man of value.',
 'It is better to be hated for what you are than to be loved for what you are not.',
 "I have not failed. I've just found 10,000 ways that won't work.",
 "A woman is like a tea bag; you never know how strong it is until it's in hot water.",
 'A day without sunshine is like, you know, night.']

In [24]:
from collections import Counter
import string

# 텍스트 전처리 및 단어 빈도 계산
def word_frequency(texts):
    # 모든 텍스트를 소문자로 변환하고 구두점 제거
    cleaned_texts = ' '.join(texts).lower().translate(str.maketrans('', '', string.punctuation))
    # 단어 빈도 계산
    word_counts = Counter(cleaned_texts.split())
    return word_counts

# 단어 빈도 계산
word_counts = word_frequency(texts)
print(word_counts)

Counter({'is': 12, 'a': 9, 'it': 6, 'be': 6, 'to': 5, 'our': 4, 'are': 4, 'not': 4, 'you': 4, 'the': 3, 'as': 3, 'of': 3, 'what': 3, 'than': 3, 'we': 2, 'have': 2, 'thinking': 2, 'without': 2, 'that': 2, 'ways': 2, 'though': 2, 'miracle': 2, 'in': 2, 'its': 2, 'better': 2, 'absolutely': 2, 'become': 2, 'man': 2, 'for': 2, 'like': 2, 'know': 2, 'world': 1, 'created': 1, 'process': 1, 'cannot': 1, 'changed': 1, 'changing': 1, 'choices': 1, 'harry': 1, 'show': 1, 'truly': 1, 'far': 1, 'more': 1, 'abilities': 1, 'there': 1, 'only': 1, 'two': 1, 'live': 1, 'your': 1, 'life': 1, 'one': 1, 'nothing': 1, 'other': 1, 'everything': 1, 'person': 1, 'gentleman': 1, 'or': 1, 'lady': 1, 'who': 1, 'has': 1, 'pleasure': 1, 'good': 1, 'novel': 1, 'must': 1, 'intolerably': 1, 'stupid': 1, 'imperfection': 1, 'beauty': 1, 'madness': 1, 'genius': 1, 'and': 1, 'ridiculous': 1, 'boring': 1, 'try': 1, 'success': 1, 'rather': 1, 'value': 1, 'hated': 1, 'loved': 1, 'i': 1, 'failed': 1, 'ive': 1, 'just': 1, 'found': 1, '10000': 1, 'wont': 1, 'work': 1, 'woman': 1, 'tea': 1, 'bag': 1, 'never': 1, 'how': 1, 'strong': 1, 'until': 1, 'hot': 1, 'water': 1, 'day': 1, 'sunshine': 1, 'night': 1})

# Feature Representation
# Representation Learning = Machine Learning

In [12]:
texts

['The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.',
 'It is our choices, Harry, that show what we truly are, far more than our abilities.',
 'There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.',
 'The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.',
 "Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.",
 'Try not to become a man of success. Rather become a man of value.',
 'It is better to be hated for what you are than to be loved for what you are not.',
 "I have not failed. I've just found 10,000 ways that won't work.",
 "A woman is like a tea bag; you never know how strong it is until it's in hot water.",
 'A day without sunshine is like, you know, night.']

In [13]:
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(texts)
print(vectorizer.get_feature_names_out())
print(X.toarray())

['000' '10' 'abilities' 'absolutely' 'and' 'are' 'as' 'bag' 'be' 'beauty'
 'become' 'better' 'boring' 'cannot' 'changed' 'changing' 'choices'
 'created' 'day' 'everything' 'failed' 'far' 'for' 'found' 'genius'
 'gentleman' 'good' 'harry' 'has' 'hated' 'have' 'hot' 'how'
 'imperfection' 'in' 'intolerably' 'is' 'it' 'just' 'know' 'lady' 'life'
 'like' 'live' 'loved' 'madness' 'man' 'miracle' 'more' 'must' 'never'
 'night' 'not' 'nothing' 'novel' 'of' 'one' 'only' 'or' 'other' 'our'
 'person' 'pleasure' 'process' 'rather' 'ridiculous' 'show' 'strong'
 'stupid' 'success' 'sunshine' 'tea' 'than' 'that' 'the' 'there'
 'thinking' 'though' 'to' 'truly' 'try' 'two' 'until' 'value' 've' 'water'
 'ways' 'we' 'what' 'who' 'without' 'woman' 'won' 'work' 'world' 'you'
 'your']
[[0 0 0 0 0 0 1 0 1 0 0 0 0 1 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0
  1 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 2 0 0 1 0 0 0 0 0 0 0 0
  0 0 1 0 2 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 1 0 0]
 [0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0
  1 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 1 0 0 0 0 0
  1 1 0 0 0 0 0 1 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 2 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  4 0 0 0 0 1 0 1 0 0 0 2 0 0 0 0 0 1 0 0 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 1 1 0 2 1 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 0 0 0 0 0 1 1
  0 1 0 0 1 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 0 0 1 0 0 1 1 0 0 0 0 0 1 0 0 0
  0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 2 1 0 0 0 1 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0
  2 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0
  1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 1 0 0 2 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0
  0 0 0 0 0 0 1 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 2 0 0 2 0 0 1 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 1 0 0 0 0 0 0
  1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  1 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 2 0]
 [1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0
  0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 1 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 1 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 0
  2 2 0 1 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1
  0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 1 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  1 0 0 1 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0]]

In [14]:
pd.DataFrame(X.toarray(),
             columns = vectorizer.get_feature_names_out())

,000,10,abilities,absolutely,and,are,as,bag,be,beauty,...,we,what,who,without,woman,won,work,world,you,your
0,0,0,0,0,0,0,1,0,1,0,...,1,0,0,1,0,0,0,1,0,0
1,0,0,1,0,0,1,0,0,0,0,...,1,1,0,0,0,0,0,0,0,0
2,0,0,0,0,0,1,2,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3,0,0,0,0,0,0,0,0,2,0,...,0,0,1,0,0,0,0,0,0,0
4,0,0,0,2,1,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,0,0,0,0,0,2,0,0,2,0,...,0,2,0,0,0,0,0,0,2,0
7,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,1,0,0,0
8,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,1,0,0,0,1,0
9,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,1,0

## 10페이지 까지 인용문 읽기(gemini)

In [30]:
import requests
from bs4 import BeautifulSoup
import time

base_url = "http://quotes.toscrape.com"
current_url = base_url
page_count = 1

# 1. 데이터를 담을 빈 리스트 생성
all_quotes = []

print("🚀 데이터 수집 및 리스트 저장 시작...")

while page_count <= 10:
    response = requests.get(current_url)
    soup = BeautifulSoup(response.text, "html.parser")

    # 현재 페이지의 모든 인용문 요소 찾기
    quotes = soup.find_all("span", class_="text")

    for quote in quotes:
        # 2. 리스트에 인용문 텍스트 추가
        all_quotes.append(quote.text)

    # 다음 페이지 이동 로직
    next_button = soup.find("li", class_="next")
    if next_button and page_count < 10:
        current_url = base_url + next_button.find("a")["href"]
        page_count += 1
        time.sleep(0.1) # 속도를 위해 대기 시간을 줄였습니다
    else:
        break

# 3. 결과 확인
print(f"\n✅ 수집 완료! 총 {len(all_quotes)}개의 항목이 리스트에 저장되었습니다.")
print("-" * 30)
print("처음 3개 미리보기:", all_quotes[:3])

🚀 데이터 수집 및 리스트 저장 시작...

✅ 수집 완료! 총 100개의 항목이 리스트에 저장되었습니다.
------------------------------
처음 3개 미리보기: ['“The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”', '“It is our choices, Harry, that show what we truly are, far more than our abilities.”', '“There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.”']

In [33]:
word_frequency(all_quotes)

Counter({'“the': 12,
         'world': 6,
         'as': 14,
         'we': 8,
         'have': 17,
         'created': 1,
         'it': 36,
         'is': 69,
         'a': 62,
         'process': 1,
         'of': 48,
         'our': 6,
         'thinking': 2,
         'cannot': 1,
         'be': 29,
         'changed': 1,
         'without': 6,
         'changing': 1,
         'thinking”': 2,
         '“it': 8,
         'choices': 1,
         'harry': 3,
         'that': 29,
         'show': 1,
         'what': 16,
         'truly': 2,
         'are': 16,
         'far': 1,
         'more': 11,
         'than': 9,
         'abilities”': 1,
         '“there': 5,
         'only': 9,
         'two': 2,
         'ways': 2,
         'to': 71,
         'live': 7,
         'your': 18,
         'life': 7,
         'one': 12,
         'though': 2,
         'nothing': 4,
         'miracle': 1,
         'the': 63,
         'other': 3,
         'everything': 5,
         'miracle”': 1,
         'person': 4,
         'gentleman': 1,
         'or': 12,
         'lady': 1,
         'who': 18,
         'has': 6,
         'not': 33,
         'pleasure': 1,
         'in': 26,
         'good': 7,
         'novel': 1,
         'must': 5,
         'intolerably': 1,
         'stupid”': 1,
         '“imperfection': 1,
         'beauty': 1,
         'madness': 1,
         'genius': 3,
         'and': 48,
         'its': 13,
         'better': 3,
         'absolutely': 2,
         'ridiculous': 1,
         'boring”': 1,
         '“try': 1,
         'become': 4,
         'man': 5,
         'success': 1,
         'rather': 1,
         'value”': 1,
         'hated': 1,
         'for': 12,
         'you': 84,
         'loved': 2,
         'not”': 1,
         '“i': 11,
         'failed': 1,
         'ive': 2,
         'just': 7,
         'found': 1,
         '10000': 1,
         'wont': 1,
         'work”': 1,
         '“a': 7,
         'woman': 2,
         'like': 9,
         'tea': 2,
         'bag': 1,
         'never': 12,
         'know': 7,
         'how': 6,
         'strong': 1,
         'until': 3,
         'hot': 1,
         'water”': 1,
         'day': 7,
         'sunshine': 1,
         'night”': 1,
         '“this': 1,
         'make': 10,
         'no': 12,
         'matter': 2,
         'youre': 4,
         'going': 7,
         'mess': 2,
         'up': 13,
         'sometimes': 1,
         'universal': 1,
         'truth': 6,
         'but': 25,
         'part': 2,
         'get': 5,
         'decide': 1,
         'girls': 1,
         'will': 18,
         'friends': 5,
         'theyll': 2,
         'act': 1,
         'anyway': 1,
         'remember': 4,
         'some': 5,
         'come': 5,
         'go': 5,
         'ones': 2,
         'stay': 1,
         'with': 13,
         'through': 2,
         'theyre': 1,
         'true': 2,
         'best': 4,
         'dont': 8,
         'let': 5,
         'them': 7,
         'also': 2,
         'sisters': 1,
         'lovers': 1,
         'well': 3,
         'too': 4,
         'baby': 1,
         'i': 39,
         'hate': 3,
         'say': 2,
         'most': 3,
         'actually': 1,
         'pretty': 1,
         'much': 5,
         'all': 14,
         'break': 1,
         'heart': 3,
         'cant': 2,
         'give': 7,
         'because': 9,
         'if': 14,
         'youll': 4,
         'find': 4,
         'soulmate': 1,
         'half': 2,
         'makes': 4,
         'whole': 1,
         'goes': 1,
         'fail': 3,
         'once': 1,
         'doesnt': 5,
         'mean': 2,
         'gonna': 1,
         'at': 7,
         'keep': 7,
         'trying': 3,
         'hold': 2,
         'on': 6,
         'always': 4,
         'believe': 5,
         'yourself': 2,
         'then': 3,
         'sweetie': 1,
         'so': 10,
         'head': 2,
         'high': 3,
         'chin': 1,
         'importantly': 1,
         'smiling': 2,
         'lifes': 1,
         'beautiful': 2,
         'thing': 5,
         'theres': 1,
         'smile': 2,
         'about”': 1,
         'takes': 2,
         'great': 5,
         'deal': 1,
         'bravery': 1,
         'stand': 2,
         'enemies': 1,
         'friends”': 1,
         '“if': 7,
         'explain': 1,
         'six': 1,
         'year': 1,
         'old': 3,
         'understand': 2,
         'yourself”': 3,
         '“you': 7,
         'may': 7,
         'her': 11,
         'first': 1,
         'last': 2,
         'she': 11,
         'before': 3,
         'love': 19,
         'again': 1,
         'loves': 1,
         'now': 3,
         'else': 3,
         'matters': 2,
         'shes': 2,
         'perfect—you': 1,
         'arent': 1,
         'either': 1,
         'perfect': 1,
         'together': 1,
         'can': 19,
         'laugh': 2,
         'cause': 1,
         'think': 11,
         'twice': 1,
         'admit': 1,
         'being': 1,
         'human': 2,
         'making': 2,
         'mistakes': 1,
         'onto': 1,
         'about': 4,
         'every': 5,
         'second': 1,
         'knows': 1,
         'break—her': 1,
         'hurt': 3,
         'change': 2,
         'analyze': 1,
         'expect': 1,
         'when': 10,
         'happy': 1,
         'mad': 1,
         'miss': 1,
         'there”': 1,
         'nonsense': 1,
         'wakes': 1,
         'brain': 1,
         'cells': 1,
         'fantasy': 1,
         'necessary': 2,
         'ingredient': 1,
         'living”': 1,
         'gone': 1,
         'where': 3,
         'intended': 1,
         'ended': 1,
         'needed': 1,
         'be”': 3,
         'opposite': 4,
         'indifference': 3,
         'art': 1,
         'ugliness': 1,
         'faith': 1,
         'heresy': 1,
         'death': 3,
         'indifference”': 1,
         'lack': 2,
         'friendship': 1,
         'unhappy': 1,
         'marriages”': 1,
         '“good': 1,
         'books': 3,
         'sleepy': 1,
         'conscience': 1,
         'this': 3,
         'ideal': 1,
         'life”': 1,
         '“life': 3,
         'happens': 4,
         'us': 4,
         'while': 2,
         'plans”': 1,
         'knowing': 1,
         'from': 9,
         'simply': 1,
         'problems': 1,
         'pride': 1,
         'way': 5,
         'do': 9,
         'any': 3,
         'loving': 2,
         'which': 4,
         'there': 4,
         'intimate': 2,
         'hand': 2,
         'upon': 1,
         'my': 13,
         'chest': 1,
         'fall': 1,
         'asleep': 1,
         'eyes': 2,
         'close”': 1,
         '“for': 1,
         'minute': 1,
         'angry': 1,
         'lose': 1,
         'sixty': 1,
         'seconds': 1,
         'happiness”': 1,
         'judge': 1,
         'people': 7,
         'time': 6,
         'them”': 1,
         '“anyone': 2,
         'thinks': 2,
         'sitting': 2,
         'church': 1,
         'christian': 1,
         'garage': 1,
         'car”': 1,
         '“beauty': 1,
         'eye': 1,
         'beholder': 2,
         'stupid': 1,
         'misinformed': 1,
         'black': 1,
         'eye”': 1,
         '“today': 1,
         'truer': 1,
         'alive': 1,
         'youer': 1,
         'you”': 2,
         'want': 4,
         'children': 1,
         'intelligent': 2,
         'read': 5,
         'fairy': 3,
         'tales': 2,
         'tales”': 1,
         'impossible': 1,
         'failing': 1,
         'something': 4,
         'unless': 1,
         'cautiously': 1,
         'might': 2,
         'lived': 1,
         'case': 1,
         'by': 5,
         'default”': 1,
         '“logic': 1,
         'z': 1,
         'imagination': 2,
         'everywhere”': 1,
         '“one': 1,
         'music': 3,
         'hits': 1,
         'feel': 2,
         'pain”': 1,
         'things': 5,
         'learn': 2,
         'places': 1,
         'go”': 1,
         '“of': 1,
         'course': 2,
         'happening': 1,
         'inside': 2,
         'why': 1,
         'earth': 1,
         'should': 3,
         'real”': 1,
         'everyone': 4,
         'got': 2,
         'worth': 1,
         'suffering': 1,
         'for”': 1,
         '“not': 2,
         'small': 2,
         'love”': 3,
         '“to': 3,
         'wellorganized': 1,
         'mind': 3,
         'next': 1,
         'adventure”': 2,
         '“all': 1,
         'need': 1,
         'little': 3,
         'chocolate': 1,
         'hurt”': 1,
         '“we': 2,
         'were': 3,
         'alone”': 1,
         '“any': 1,
         'fool': 1,
         'point': 2,
         'understand”': 1,
         'imagined': 1,
         'paradise': 1,
         'kind': 3,
         'library”': 2,
         'late': 1,
         'been”': 1,
         'reader': 1,
         'lives': 5,
         'thousand': 1,
         'he': 2,
         'dies': 1,
         'said': 1,
         'jojen': 1,
         'reads': 1,
         'one”': 2,
         'cup': 1,
         'large': 1,
         'enough': 3,
         'book': 6,
         'long': 2,
         'suit': 1,
         'me”': 3,
         'lies': 1,
         'eventually': 1,
         'trust': 1,
         'anything”': 1,
         'riding': 1,
         'bicycle': 1,
         'balance': 1,
         'moving”': 1,
         'real': 1,
         'lover': 1,
         'thrill': 1,
         'kissing': 1,
         'forehead': 1,
         'into': 2,
         'staring': 1,
         'space”': 1,
         'wise': 1,
         'girl': 2,
         'kisses': 1,
         'listens': 1,
         'leaves': 1,
         'left”': 1,
         '“only': 1,
         'darkness': 1,
         'see': 7,
         'stars”': 1,
         'someone': 2,
         'born': 1,
         'they': 2,
         'grow': 2,
         '“love': 1,
         'does': 2,
         'begin': 2,
         'end': 1,
         'seem': 1,
         'battle': 1,
         'war': 1,
         'growing': 1,
         'up”': 1,
         'would': 2,
         'those': 3,
         'really': 5,
         'notion': 1,
         'halves': 1,
         'nature”': 1,
         '“do': 2,
         'scares': 1,
         'am': 5,
         'an': 6,
         'angel': 1,
         'sin': 1,
         'devil': 1,
         'big': 3,
         'physicist': 1,
         'probably': 1,
         'musician': 1,
         'often': 2,
         'daydreams': 1,
         'terms': 1,
         'music”': 1,
         'reading': 4,
         'difference': 1,
         'between': 2,
         'stupidity': 1,
         'limits”': 1,
         '“hes': 1,
         'drug': 1,
         'bella”': 1,
         'friend': 2,
         'loyal': 1,
         'book”': 1,
         '“when': 1,
         'door': 2,
         'happiness': 1,
         'closes': 1,
         'another': 1,
         'opens': 1,
         'look': 1,
         'closed': 1,
         'been': 1,
         'opened': 1,
         'us”': 1,
         'isnt': 2,
         'finding': 1,
         'creating': 1,
         '“thats': 1,
         'problem': 1,
         'drinking': 1,
         'thought': 2,
         'poured': 1,
         'myself': 2,
         'drink': 4,
         'bad': 1,
         'attempt': 1,
         'forget': 3,
         'order': 1,
         'celebrate': 1,
         'happen”': 1,
         'don’t': 1,
         'face': 1,
         'was': 3,
         'hope”': 1,
         '“remember': 2,
         'madly': 1,
         'right': 3,
         'kiss': 1,
         'me': 5,
         'anytime': 1,
         'it”': 4,
         'vulnerable': 1,
         'anything': 2,
         'wrung': 1,
         'possibly': 1,
         'broken': 2,
         'sure': 1,
         'keeping': 1,
         'intact': 1,
         'even': 1,
         'animal': 1,
         'wrap': 1,
         'carefully': 1,
         'round': 1,
         'hobbies': 1,
         'luxuries': 1,
         'avoid': 1,
         'entanglements': 1,
         'lock': 1,
         'safe': 2,
         'casket': 2,
         'coffin': 1,
         'selfishness': 1,
         'dark': 1,
         'motionless': 1,
         'airless': 1,
         'unbreakable': 1,
         'impenetrable': 1,
         'irredeemable': 1,
         'vulnerable”': 1,
         'wander': 1,
         'lost”': 1,
         'pity': 2,
         'dead': 1,
         'living': 1,
         'above': 1,
         'writing': 1,
         'sit': 1,
         'down': 1,
         'typewriter': 1,
         'bleed”': 1,
         '“finish': 1,
         'each': 1,
         'done': 3,
         'could': 3,
         'blunders': 1,
         'absurdities': 1,
         'doubt': 1,
         'crept': 1,
         'soon': 1,
         'tomorrow': 1,
         'new': 1,
         'shall': 2,
         'serenely': 1,
         'spirit': 1,
         'encumbered': 1,
         'nonsense”': 1,
         'schooling': 1,
         'interfere': 1,
         'education”': 1,
         'heard': 1,
         'troubles': 3,
         'ahead': 1,
         'behind': 1,
         'bought': 1,
         'bat': 1,
         'im': 3,
         'ready': 1,
         'had': 1,
         'flower': 1,
         'youi': 1,
         'walk': 2,
         'garden': 1,
         'forever”': 1,
         '“some': 2,
         'crazy': 1,
         'horrible': 1,
         'lead”': 1,
         'trouble': 1,
         'having': 1,
         'open': 1,
         'insist': 1,
         'coming': 1,
         'along': 1,
         'put': 1,
         '“think': 1,
         'left': 1,
         'low': 1,
         'oh': 1,
         'try”': 1,
         '“what': 1,
         'knocks': 1,
         'out': 2,
         'wish': 1,
         'author': 1,
         'wrote': 1,
         'terrific': 1,
         'yours': 1,
         'call': 1,
         'him': 1,
         'phone': 1,
         'whenever': 1,
         'felt': 1,
         'happen': 1,
         'though”': 1,
         'reason': 1,
         'talk': 1,
         'i’m': 1,
         'whose': 1,
         'answers': 1,
         'accept”': 1,
         'dreamer': 1,
         'hope': 1,
         'someday': 1,
         'join': 1,
         'free': 1,
         'prejudice': 1,
         'equally': 1,
         '”': 1,
         'question': 1,
         'stop': 1,
         '“′classic′': 1,
         'praise': 1,
         'read”': 1,
         'made': 1,
         'mistake': 1,
         'tried': 1,
         'new”': 1,
         'ladys': 1,
         'very': 1,
         'rapid': 1,
         'jumps': 1,
         'admiration': 1,
         'matrimony': 1,
         'moment”': 1,
         'choice': 1,
         'easy': 1,
         'happened': 1,
         'boy': 1,
         'brave': 1,
         'strayed': 1,
         'across': 1,
         'path': 1,
         'lord': 1,
         'voldemort': 1,
         'cedric': 1,
         'diggory”': 1,
         'declare': 1,
         'after': 1,
         'enjoyment': 1,
         'sooner': 1,
         'tires': 1,
         'house': 1,
         'own': 1,
         'miserable': 1,
         'excellent': 1,
         'few': 1,
         'whom': 2,
         'still': 1,
         'fewer': 1,
         'dissatisfied': 1,
         'confirms': 1,
         'belief': 1,
         'inconsistency': 1,
         'characters': 1,
         'dependence': 1,
         'placed': 1,
         'appearance': 1,
         'merit': 1,
         'sense”': 1,
         'start': 1,
         'again”': 1,
         'necessarily': 1,
         'doubting': 1,
         'god': 1,
         'wondering': 1,
         'painful': 1,
         'turn': 1,
         'fear': 2,
         'follows': 1,
         'fully': 1,
         'prepared': 1,
         'die': 4,
         'time”': 1,
         'lie': 1,
         'travel': 1,
         'around': 2,
         'putting': 1,
         'shoes”': 1,
         'christianity': 1,
         'sun': 1,
         'risen': 1,
         'else”': 1,
         'dumbledore': 1,
         'sighed': 1,
         'terrible': 1,
         'therefore': 1,
         'treated': 1,
         'caution”': 1,
         '“im': 1,
         'thats': 1,
         'to”': 1,
         'awfully': 1,
         'courage': 1,
         'are”': 1,
         '“but': 1,
         'comforted': 1,
         'lie”': 1,
         'consider': 1,
         'his': 2,
         'view': 1,
         'climb': 1,
         'skin': 1,
         'write': 2,
         'wants': 1,
         'written': 1,
         'difficult': 1,
         'grownups': 1,
         'children”': 1,
         '“never': 1,
         'tell': 1,
         'worthy': 1,
         'persons': 1,
         'small”': 1,
         '“': 1,
         'needs': 2,
         'sword': 1,
         'whetstone': 1,
         'edge”': 1})

In [35]:
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(all_quotes)

In [36]:
pd.DataFrame(X.toarray(),
             columns = vectorizer.get_feature_names_out())

,000,10,abilities,about,above,absolutely,absurdities,accept,across,act,...,writing,written,wrote,wrung,year,you,youer,your,yours,yourself
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,2,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,3,0,0,0,0
96,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,2,0,0,0,0
97,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
98,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
99,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0